server:
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DATABASE}?characterEncoding=UTF-8
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database: mysql
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      default_batch_fetch_size: 100
logging:
  level:
    '[com.tag.prietag]': INFO # DEBUG 레벨부터 에러 확인할 수 있게 설정하기

jwt:
  secret: ${SECRET}

# S3
cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESSKEY}
      secret-key: ${S3_SECRETKEY}
    region:
      static: ${S3_REGION}
    s3:
      bucket: ${S3_NAME}
    stack:
      auto: false
